// Package swagger provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.0 DO NOT EDIT.
package swagger

// PaginatedValues defines model for PaginatedValues.
type PaginatedValues struct {
	HasMore bool             `json:"hasMore"`
	Values  []TelemetryValue `json:"values"`
}

// TelemetryValue defines model for TelemetryValue.
type TelemetryValue struct {
	OccuranceAt string  `json:"occurance_at"`
	Value       float32 `json:"value"`
}

// Page defines model for page.
type Page = int

// Perpage defines model for perpage.
type Perpage = int

// TelemetryPaginatedParams defines parameters for TelemetryPaginated.
type TelemetryPaginatedParams struct {
	Page    *Page    `form:"page,omitempty" json:"page,omitempty"`
	PerPage *Perpage `form:"perPage,omitempty" json:"perPage,omitempty"`
}
