openapi: 3.0.3
info:
  title: Телеметрия устройства
  version: '1.0'
  description: API для работы с сервисом Телеметрии
paths:
  /devices/{module_id}/{device_id}/telemetry/latest:
    get:
      summary: Получение последнего значения телеметрии
      operationId: telemetryLatests
      parameters:
        - name: module_id
          description: Идентификатор блока устройства
          required: true
          in: path
          schema:
            type: integer
        - name: device_id
          description: Идентификатор устройства
          required: true
          in: path
          schema:
            type: integer  
      responses:
      responses:
        200:
          description: Информация по устройству
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TelemetryValue'
        404:
          $ref: '#/components/responses/NotFoundError' 
  /devices/{module_id}/{device_id}/telemetry:
    get:
      summary: Получение данных телеметрии
      parameters:
        - name: module_id
          description: Идентификатор блока устройства
          required: true
          in: path
          schema:
            type: integer
        - name: device_id
          description: Идентификатор устройства
          required: true
          in: path
          schema:
            type: integer  
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/perpage'
      operationId: telemetryRead
      responses:
        200:
          description: Список значений
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/PaginatedResult'
                  - type: object
                    properties:
                      results:
                        type: array
                        items:
                          $ref: '#/components/schemas/TelemetryValue'  
components:
  responses:
    Success:
      description: Успех
    NotFoundError:
      description: Устройство не найдено
  parameters:
    page:
      in: query
      name: page
      schema:
        type: integer
        example: 1
    perpage:
      in: query
      name: per_page
      schema:
        type: integer
        example: 15
        default: 10
  schemas:
    TelemetryValue:
      type: object
      properties:
        value:
          type: float
        occurance_at:
          type: string      
    PaginatedResult:
      type: object
      properties:
        page:
          type: number
          example: 3
        per_page:
          type: number
          example: 20
        hasMore:
          type: boolean
          example: false
        results:
          type: array
          items: {}
