// Package swagger provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.0 DO NOT EDIT.
package swagger

// Defines values for DeviceValueValueName.
const (
	Status      DeviceValueValueName = "status"
	TargetValue DeviceValueValueName = "target_value"
)

// DeviceInfo Информация по устройству
type DeviceInfo struct {
	// SerialNumber Серийный номер устройства
	SerialNumber string `json:"serial_number"`

	// Status Статус устройства - вкл/выкл
	Status bool `json:"status"`

	// Type Тип устройства
	Type string `json:"type"`
}

// DeviceValue Новый статус или целевое значение
type DeviceValue struct {
	// Status Значение статуса устройства (вкл/выкл)
	Status *bool `json:"status,omitempty"`

	// TargetValue Целевое значение
	TargetValue *float32 `json:"target_value,omitempty"`

	// ValueName Какое значение передаётся
	ValueName DeviceValueValueName `json:"value_name"`
}

// DeviceValueValueName Какое значение передаётся
type DeviceValueValueName string

// DeviceSetValueJSONRequestBody defines body for DeviceSetValue for application/json ContentType.
type DeviceSetValueJSONRequestBody = DeviceValue
