openapi: 3.0.3
info:
  title: Управление устройствами
  version: '1.0'
  description: API для управления устройствами
paths:
  /devices/{module_id}/{device_d}/get:
    get:
      summary: Получить информацию по устройству
      operationId: deviceInfo
      parameters:
        - name: module_id
          description: Идентификатор блока устройства
          required: true
          in: path
          schema:
            type: integer
        - name: device_id
          description: Идентификатор устройства
          required: true
          in: path
          schema:
            type: integer        
      responses:
        200:
          description: Информация по устройству
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceInfo'
        404:
          $ref: '#/components/responses/NotFoundError'
  /devices/{module_id}/{device_id}/set:
    post:
      summary: Установить статус или целевое значение устройства
      operationId: deviceSet
      parameters:
        - name: module_id
          description: Идентификатор блока устройства
          required: true
          in: path
          schema:
            type: integer
        - name: device_id
          description: Идентификатор устройства
          required: true
          in: path
          schema:
            type: integer        
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Values'
      responses:
        200:
          $ref: '#/components/responses/DeviceValues'
        400:
          $ref: '#/components/responses/BadRequestError'
        404:
          $ref: '#/components/responses/NotFoundError'
      
components:
  responses:
    Success:
      description: Успех
    NotFoundError:
      description: Устройство не найдено
    BadRequestError:
      description: Ошибка входных данных
  schemas:
    DeviceInfo:
      type: object
      description: Информация по устройству
      properties:
        type:
          type: string
          description: Тип устройства
        serial_number:
          type: string
          description: Серийный номер устройства
        status:
          type: boolean
          description: Статус устройства - вкл/выкл
    DeviceValues:
      type: object
      description: Новый статус или целевое значение
      properties:
        target_value:
          type: float
          description: Целевое значение
          required: false
        status:
          type: boolean
          description: Статус устройства (вкл/выкл)
          required: false
